name: xbmkg
description: "Aplikasi Cuaca dan Gempa Bumi Indonesia"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  provider: ^6.1.2
  fl_chart: ^0.69.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
