name: xbmkg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  assets:
  - assets/lottie/
  uses-material-design: true
